name: Publish
on:
  workflow_dispatch:
    inputs:
      publish-to-ghcr-npm:
        type: boolean
        description: "Publish release to npm (ghcr)"
        default: true


jobs:
  publish:
    name: Publish to GHCR NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: yarn install

      - name: Generate types
        run: yarn tsc

      - name: Build
        run: yarn build

      - name: Publish if version has been updated
        if: inputs.publish-to-ghcr-npm
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com/HBK-IDP"
          access: "restricted"

